all :
	chmod 777 *

base : all
	./linux-secret-agent.zsh 10 &

advanced : all
	nohup ./linux-secret-agent.zsh 5

intelligence : all
	./linux-intelligence.zsh &

evil : all
	zsh final.sh

zombie : all
